apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: flink-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://downloads.apache.org/flink/flink-kubernetes-operator-0.1.0/

